### PR TITLE
(PR) Updated The Documentation

### PR DESCRIPTION
**Pull request by TebogoYungMercykay**
# Files Updated

- Architectural Specification
- Technical installation
- Delivery Specification
- Coding Standards

### CODE REVIEW

**Comment by MulisaMusehane** [comment]
@TebogoYungMercykay I updated the links and added the testing specification here ` https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567 `

There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...

**Review by ShamaKamina — COMMENTED** [review]
i dont think its necessary to put both MD and PDF the spec says PDF only. also this title 

"Links to the Latest Documentation of the Project as of 30 September 2024" is too much. Just "Links to the Documentation" is sufficient I think

**Comment by MulisaMusehane** [comment]
> i dont think its necessary to put both MD and PDF the spec says PDF only. also this title
> 
> "Links to the Latest Documentation of the Project as of 30 September 2024" is too much. Just "Links to the Documentation" is sufficient I think

Alright, feel free to fix it 👊🏿

**Comment by hlokomani** [comment]
> > i dont think its necessary to put both MD and PDF the spec says PDF only. also this title
> 
> > 
> 
> > "Links to the Latest Documentation of the Project as of 30 September 2024" is too much. Just "Links to the Documentation" is sufficient I think
> 
> 
> 
> Alright, feel free to fix it 👊🏿

😭😭😭

**Comment by MulisaMusehane** [comment]
@ShamaKamina looks good, nice

**Comment by ShamaKamina** [comment]
@MulisaMusehane Did you add the use case diagrams on the Requirement spec pdf? I dont see them on my side and I am not sure whther its a problem on my side only

**Comment by TebogoYungMercykay** [comment]
> @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> 
> There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...

I have added the PDFs just now, Double check and yeah

**Comment by TebogoYungMercykay** [comment]
Damn, Closed PR by Mistake...

gustavo

**Comment by ShamaKamina** [comment]
> > @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> > There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...
> 
> I have added the PDFs just now, Double check and yeah

Eh you made changes? I already did everything

**Comment by MulisaMusehane** [comment]
> > > @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> > > There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...
> > 
> > 
> > I have added the PDFs just now, Double check and yeah
> 
> Eh you made changes? I already did everything

He made updates on the .md. The PDF you used was the old one... he had to convert the new updated user manual that has pictures to PDF bc the one we initially used, which you refed earlier when fixing does not have pictures :)

**Comment by ShamaKamina** [comment]
> > > > @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> > > > There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...
> > > 
> > > 
> > > I have added the PDFs just now, Double check and yeah
> > 
> > 
> > Eh you made changes? I already did everything
> 
> He made updates on the .md. The PDF you used was the old one... he had to convert the new updated user manual that has pictures to PDF bc the one we initially used, which you refed earlier when fixing does not have pictures :)

Yes i made those changes already

**Comment by ShamaKamina** [comment]
please check the logs of this pr homies

**Comment by TebogoYungMercykay** [comment]
@ShamaKamina, are you saying that you added the PDFs on your side as well? In that case, we could use the ones you added. I just read the responses and thought no one added them since they didn't show in the code.

**Comment by ShamaKamina** [comment]
> @ShamaKamina, are you saying that you added the PDFs on your side as well? In that case, we could use the ones you added. I just read the responses and thought no one added them since they didn't show in the code.

yes i already added the pdfs with images for the requirement spec and the user manual

**Comment by MulisaMusehane** [comment]
> > > > > @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> > > > > There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...
> > > > 
> > > > 
> > > > I have added the PDFs just now, Double check and yeah
> > > 
> > > 
> > > Eh you made changes? I already did everything
> > 
> > 
> > He made updates on the .md. The PDF you used was the old one... he had to convert the new updated user manual that has pictures to PDF bc the one we initially used, which you refed earlier when fixing does not have pictures :)
> 
> Yes i made those changes already



> > > > > @TebogoYungMercykay I updated the links and added the testing specification here `https://github.com/COS301-SE-2024/The-Republic/pull/372/commits/003a58634d2967f266c2fc220d3b9605bd235567`
> > > > > There is only one link that will not work which is the PDF to the UserManualVersion4.pdf - can you pls use the extension you used to get the .md of it to pdf bc there are links to images and if I gotta use latex for it, it'll take a while...
> > > > 
> > > > 
> > > > I have added the PDFs just now, Double check and yeah
> > > 
> > > 
> > > Eh you made changes? I already did everything
> > 
> > 
> > He made updates on the .md. The PDF you used was the old one... he had to convert the new updated user manual that has pictures to PDF bc the one we initially used, which you refed earlier when fixing does not have pictures :)
> 
> Yes i made those changes already

Alright cool

**Comment by ShamaKamina** [comment]
sigh

image

**Comment by TebogoYungMercykay** [comment]
I see. And the changes you made were overwritten by [this commit](https://github.com/COS301-SE-2024/The-Republic/commit/d2fbf53e9cb5b2a16f211cd5b506130caa327840), After this, the User Manual without the images became the latest change.

**Comment by ShamaKamina** [comment]
> @ShamaKamina I see. And the changes you made were overwritten by [this commit](https://github.com/COS301-SE-2024/The-Republic/commit/d2fbf53e9cb5b2a16f211cd5b506130caa327840), After this, the User Manual without the images became the latest change.

Alright. You can fix whatever needs to be fixed

**Comment by TebogoYungMercykay** [comment]
> > @ShamaKamina I see. And the changes you made were overwritten by [this commit](https://github.com/COS301-SE-2024/The-Republic/commit/d2fbf53e9cb5b2a16f211cd5b506130caa327840), After this, the User Manual without the images became the latest change.
> 
> Alright. You can fix whatever needs to be fixed

I think everything is linked properly.

**Review by ShamaKamina — APPROVED** [review]

**Pull request merged**
