### PR TITLE
Added commenting and updated backed

### LINKED ISSUE #84: Add comment functionality to backend
### Description

We need to implement a commenting feature on the backend that allows users to add, edit, and delete comments on issues. This feature should include creating the necessary database schema, implementing CRUD operations, and creating API endpoints to interact with the frontend.

#### Subtasks

- [ ] **Database Schema**
  - [ ] Create a `comments` table with the following fields:
    - `comment_id` (Primary Key, UUID)
    - `issue_id` (Foreign Key, references `issues.issue_id`)
    - `user_id` (Foreign Key, references `users.user_id`)
    - `content` (Text)
    - `created_at` (Timestamp)
    - `updated_at` (Timestamp)
  - [ ] Add necessary indexes and foreign key constraints.

- [ ] **Repository**
  - [ ] Create a `CommentRepository` for interacting with the `comments` table.
  - [ ] Implement the following methods in `CommentRepository`:
    - `createComment(comment: Partial<Comment>): Promise<Comment>`
    - `getCommentsByIssueId(issueId: string): Promise<Comment[]>`
    - `deleteComment(commentId: string): Promise<void>`

- [ ] **Service**
  - [ ] Create a `CommentService` to handle business logic.
  - [ ] Implement the following methods in `CommentService`:
    - `addComment(comment: Partial<Comment>): Promise<Comment>`
    - `getCommentsForIssue(issueId: string): Promise<Comment[]>`
    - `removeComment(commentId: string): Promise<void>`

- [ ] **Controller**
  - [ ] Create a `CommentController` to handle HTTP requests.
  - [ ] Implement the following endpoints:
    - `POST /comments` to add a new comment
    - `GET /issues/:issueId/comments` to get comments for a specific issue
    - `DELETE /comments/:commentId` to delete a comment

- [ ] **Routes**
  - [ ] Create routes for the `CommentController` endpoints.
  - [ ] Ensure routes are protected and require authentication.

#### Reference Implementations

For reference, you can look at the existing implementation of the issue and reaction functionalities, as they share similar architectural and design patterns:

- **Issue Functionality**: Refer to the `IssueRepository`, `IssueService`, and `IssueController` for CRUD operations and business logic.
- **Reaction Functionality**: Look at the `ReactionRepository`, `ReactionService`, and `ReactionController` for how reactions are managed.

These references should provide a good starting point and guide for implementing the commenting feature.

#### Additional Notes

- Ensure that all inputs are properly validated and sanitized.

### PR DESCRIPTION
**Pull request by IRIA7**
closes #84 

### Comments
- Added commenting
  - Getting comments
  - Getting number of comments
  - Adding comments
  - Deleting comments
  - Can pass parent_id to make the routes apply to the replies of a comment

### Issues
- Allowed filtering by category and mood

### Middleware
- Created middleware to verify JWT and get user info
  - Users without a valid JWT will not be able to create issues, comments or reactions 

### Frontend
- Updated Feed, Reaction and UserContext to read new response format
- Fixed bug with reactions where they would go from 2 to 0

### Other
- Added user authorization:
   - An unsuccessful response will be returned if a user tries to change an issue or comment they don't own
- Added pagination for getting issues and comments
  - `from` is the index to start from and `amount` is the number of items
  - Requests would go:
  - `{ from: 0, amount: 10}`
  - `{ from: 10, amount: 10}`
  - `{ from: 20, amount: 10}`
  - And so on 
- Updated all routes to send responses following API spec
- Updated most routes to take all parameters in the body 
   - This was to simplify the code, we may change it later

Screenshot from 2024-06-16 13-39-19

### CODE REVIEW

**Comment by hlokomani** [comment]
Yo bro please check the failing unit tests

**Comment by IRIA7** [comment]
Yeah, I've just updated them 🤝

**Review by hlokomani — APPROVED** [review]
Nice work man

**Review by TebogoYungMercykay — COMMENTED** [review]
NIce work.

**Pull request merged**
