### PR TITLE
Feature/update qualityreq

### PR DESCRIPTION
**Pull request by MulisaMusehane**
**Documentation Updates and Feature Additions**

This PR includes several important updates to our project documentation and introduces new features. We've created and renamed documents The quality requirements, user stories, subsystems, and functional requirements explanations have been updated mainly for clustering, gamification, and resolution processes.. Naming conventions have been fixed across multiple files for consistency.

Some headings have been marked with TODOs for future updates, ensuring we keep track of areas that need further attention.

### CODE REVIEW

**Comment by ShamaKamina** [comment]
@MulisaMusehane Shouldn't the usermanual be version 2 which is already on the main?

**Comment by MulisaMusehane** [comment]
@ShamaKamina 

I did not work on the User Manual so I’m not sure. I worked on the Architectural and Requirements Specifications - those are the ones I updated with the new subsystems. Please refer to commit history for more detailed changes

**Comment by ShamaKamina** [comment]
@MulisaMusehane It is not shown on the history however on files changed it shows userManualVersion3.md

**Comment by MulisaMusehane** [comment]
@ShamaKamina Thanks for the clarification - it is there, peep the branch.

image

**Comment by MulisaMusehane** [comment]
@ShamaKamina There is a version 1 and 2. So not sure how we would name it version 2 when we already have it?

**Review by hlokomani — APPROVED** [review]
Looks good, we will iterate as we go on since we will have more time for documentation.

**Pull request merged**
