### PR TITLE
Updated the User Manual and the main ReadMe

### PR DESCRIPTION
**Pull request by ShamaKamina**
- Added images for the Org section on the user manual
- Updated the links on the readMe to navigate to the updated docs

### CODE REVIEW

**Comment by TebogoYungMercykay** [comment]
The images user *Creating an Organization* In the Manual are not showing.

image

**Comment by ShamaKamina** [comment]
> The images user _Creating an Organization_ In the Manual are not showing. It's because you used the filenames and not the actual file path. It seems like you used `image-x.png` instead of `path/to/image-x.png` in the doc.
> 
> image

fixed it.check again

**Review by TebogoYungMercykay — APPROVED** [review]
All good, Lrt me merge quickly.

**Review by MulisaMusehane — APPROVED** [review]
Nice Shwarms

**Pull request merged**
