### PR TITLE
Fixed IssueInputBox typescript errors

### PR DESCRIPTION
**Pull request by hlokomani**
I added an interface for the Input Box and ensured that it recieves the correct props. Feed now also passes the user prop to the Input Box, as well as ProfileStats

### CODE REVIEW

**Comment by TebogoYungMercykay** [comment]
Could you log the user object on your side, it seems to me that it's just always null.

**Comment by hlokomani** [comment]
> Could you log the user object on your side, it seems to me that it's just always null.

image
It should be null when a user isn't logged in. When a user is logged in, it isn't null. That's why I created the hook, to abstract that checking process.

You'll also notice that when not logged in, the Avatar in the IssueInputBox does not render. But when logged in, it does.
image

**Comment by TebogoYungMercykay** [comment]
Yeah I saw, Maybe instead of null let's use a default user object, And see if it solves the issue.

**Comment by hlokomani** [comment]
> I saw, Maybe instead of null let's use a defaul

Cool you're welcome to try that bro

**Comment by TebogoYungMercykay** [comment]
In the handleSubmit method we are already getting the user's session data from supabase so we could remove the prop and use that object instead to get the user data. It's somewhere around line 45-57

```
const { data, error } = await supabase.auth.getSession();

    if (error || data.session == null) {
      toast({
          description: "You need to be logged in to post",
      });
      return;
    }
```

**Review by TebogoYungMercykay — APPROVED** [review]

**Pull request merged**
