### PR TITLE
(PR) Resolution Forecasting

### LINKED ISSUE #303: Implement issue resolution forecast
Show the user how long it usually takes for an issue to be resolved

Tasks:
- [x] Implement function to calculate how long issues in a specific category and suburb take to resolve
- [x] Show this info to the user after they create an issue

### PR DESCRIPTION
**Pull request by TebogoYungMercykay**
fix #303

### CODE REVIEW

**Comment by hlokomani** [comment]
PR message?😭

**Comment by TebogoYungMercykay** [comment]
> PR message?😭

I plan to revisit the Implementation once everything is covered, It works but I feel like there could be improvements made in the way I implemented it.

**Review by ShamaKamina — APPROVED** [review]
Are you still working on it or should we merge? Everything looks okay.

**Comment by TebogoYungMercykay** [comment]
> Are you still working on it or should we merge? Everything looks okay.

Yeah, You could get it merged, I will revisit it once all the pending tickets are done with since it works. Let me resolve the conflicts.

**Pull request merged**
