### PR TITLE
(PR) Updated The Reports and Dot Visualization

### LINKED ISSUE #65: Subscribing To Channels For User Notifications
Users should be able to receive and display notifications in real-time. This feature will utilize Supabase for real-time notifications.

### Sub tasks

- [x] Integrate Supabase to subscribe to database changes
- [x] Display notifications in real-time.

- Example code on frontend:
```javascript
const channelA = supabase
        .channel('schema-db-changes')
        .on(
          'postgres_changes',
          {
            event: 'INSERT',
            schema: 'public',
            table: 'issue',
          },
          (payload) => {
            const { new: issue } = payload;
            const {names,image } = issue;
            toast.info(`New Issue`,{icon: image && <img src={issue.meta_data.image_url} alt="Profile" />,});
          }
        ).subscribe();
```

### Documentation
https://supabase.com/docs/guides/functions/examples/push-notifications

### LINKED ISSUE #66: Create reports page
The goal of this page is to ensure that users are able to view static reports on the issues reported using Nivo - documentation is below.

Generate report according to:

- [x] 1. Their municipality
- [x] 2. Any existing municipality
- [x] 3. Combine municipalities

Options for period covered on report:

- [x] 1. Daily
- [x] 2. Weekly
- [x] 3. Monthly
- [x] 4. Yearly

Inspiration: 
https://dribbble.com/shots/23930802-Reports-View
https://dribbble.com/shots/21018025-Reports-Dashboard

Documentation: https://nivo.rocks/

### LINKED ISSUE #125: Improve the charts displayed on the reports page
The charts axis labels and and titles need to be changed accordingly so that accurate information that pertains to our app is displayed.

Checklist:
- [x]  All charts have proper titles (with units if applicable)
- [x]  The axis have labels (with units if applicable)
- [x] There are legends where needed so that each graph explains what it is displaying

### PR DESCRIPTION
**Pull request by TebogoYungMercykay**
# Enhancements: Integrated Various Chart Components, Updated Layouts, Added Mock Data

**Description:**
- Integrated Radar Chart and Line Chart components.
- Added utility function for date formatting.
- Integrated Stacked Line Chart with mock data support.
- Updated headers and layouts for BarChart, DonutChart, LineChart, RadarChart, StackedChart, and TransitionChart components.
- Refactored and removed unused logs and imports.
- Fixed bugs related to Chart integration.
- Added a date formatter utility function for arrays of dates.
- Updated heading and layout for the Visualizations page.
- Updated BarChart, DonutChart, LineChart, RadarChart, StackedChart, and TransitionChart with improved layout and color schemes.
- Updated BarChart, DonutChart, LineChart, RadarChart, StackedChart, and TransitionChart with updated headers and colors.
- Added more places around Pretoria for improved data coverage.
- Implemented footer section.

# Issues
- Fix #125 
- Fix #65 
- Fix #66

### CODE REVIEW

**Review by ShamaKamina — APPROVED** [review]
Looks good! One chart has the heading "Transition of Parliament", I am not sure that pertains to our app right now. But overall great work dude :)

**Review by MulisaMusehane — APPROVED** [review]
Noice

**Comment by TebogoYungMercykay** [comment]
> Looks good! One chart has the heading "Transition of Parliament", I am not sure that pertains to our app right now. Also the words "Report" and "Dot" should be green instead of blue to adhere to the green theme we currently have going on. But overall great work dude :)

I updated the Titles Just now,  "Transition of Parliament" was the name of the chart.

**Comment by ShamaKamina** [comment]
Great work!

**Pull request merged**
