### PR TITLE
Add Google Sign-In and Improve Authentication Flow

### PR DESCRIPTION
**Pull request by hlokomani**
## Changes
1. Added Google Sign-In functionality to both login and signup pages.
2. Updated the auth callback page with a loading spinner for better UX.
3. Enhanced the CompleteProfile component to handle profile completion more securely.

### Google Sign-In
- Integrated Google Sign-In option on both login and signup pages.
- Used Supabase's `signInWithOAuth` method for seamless integration.
- Consistent styling with existing UI components.

### Auth Callback Page
- Added a loading spinner to improve user experience during authentication.
- Implemented proper error handling and logging for debugging.

## Testing
- Tested Google Sign-In flow for both new and existing users.
- Verified proper redirection after authentication.

### CODE REVIEW

**Review by TebogoYungMercykay — APPROVED** [review]

**Review by ShamaKamina — COMMENTED** [review]
I am not sure whether it is just me but the account detail at the bottom right displays my google email address and some funny user name instead of my actual name I did set up and username 

image

**Comment by MulisaMusehane** [comment]
> I am not sure whether it is just me but the account detail at the bottom right displays my google email address and some funny user name instead of my actual name I did set up and username
> 
> image

Seeing the same thing as well…

**Review by MulisaMusehane — CHANGES_REQUESTED** [review]
See @ShamaKamina screenshot King

**Comment by hlokomani** [comment]
> I am not sure whether it is just me but the account detail at the bottom right displays my google email address and some funny user name instead of my actual name I did set up and username 
> 
> 
> 
> image
> 
> 

Refresh

**Comment by ShamaKamina** [comment]
Alright its looking good. It would be nice for when a user is logging in instead that it says "Log in with Google" instead of "Sign up with google" but overall its looking good. Great work!

**Pull request merged**
