### PR TITLE
Ads

### LINKED ISSUE #302: Add ads for monetization
We should implement ads as a form of monetization. Ads should be non-intrusive but still appear frequently enough to generate revenue. They should fit in with the app's UI

### PR DESCRIPTION
**Pull request by IRIA7**
Closes #302 

Added inline banner ads to the home feed. The frequency at which the ads appear can be set. We can adjust this frequency to strike a balance between user experience and revenue, it can also be set to 0 to remove ads for paying users.

Screenshot from 2024-09-03 19-03-11

### CODE REVIEW

**Review by ShamaKamina — COMMENTED** [review]
Looks good dude thanks!

@hlokomani correct me If I am wrong but did we agree on making use of the white space on the right hand side underneath the filters for ads as well?

**Comment by hlokomani** [comment]
Could we also have mock ads that aren't our logo? Damn basically your PR is being rejected💀

**Comment by MulisaMusehane** [comment]
> Could we also have mock ads that aren't our logo? Damn basically your PR is being rejected💀

image

**Comment by TebogoYungMercykay** [comment]
> Could we also have mock ads that aren't our logo? Damn basically your PR is being rejected💀

Screenshot from 2024-07-20 11-10-36

**Review by MulisaMusehane — CHANGES_REQUESTED** [review]
image

**Comment by IRIA7** [comment]
> Could we also have mock ads that aren't our logo? Damn basically your PR is being rejected💀

GVroCUSXcAA0SQA

**Comment by IRIA7** [comment]
Added sidebar ad 👍

Screenshot from 2024-09-04 06-41-44

**Review by ShamaKamina — APPROVED** [review]
This looks so much better. Thank you, great work king.

**Pull request merged**
