### PR TITLE
Feature/username mentions

### PR DESCRIPTION
**Pull request by MulisaMusehane**
# Implement @Username Mentions UI and Interaction [Frontend]

This PR implements the frontend UI and user interaction for @username mentions in issues and comments, including autocomplete suggestions and visual highlighting.

## Changes

- Added `MentionInput` component for handling @mentions with autocomplete
- Integrated `MentionInput` into `IssueInputBox` and `AddCommentForm` components
- Implemented visual highlighting for @mentions in displayed issues and comments
- Added debounced user suggestion fetching (currently using static data, to be replaced with API call)
- Updated `Issue` component to render highlighted @mentions

## Key Features

- Users can type @ in issue and comment inputs to trigger username suggestions
- Username suggestions appear in a dropdown and can be selected via mouse or keyboard
- Selected @mentions are visually distinct in the input field
- Submitted content displays @mentions with clear highlighting
- The feature works on both desktop and mobile devices

## TODO
- Replace static user data with actual API call in `fetchUserSuggestions`

## Notes

- The current implementation limits suggestions to 5 users. This can be adjusted as needed.

## Screenshots
image
image

### CODE REVIEW

**Review by TebogoYungMercykay — CHANGES_REQUESTED** [review]
# Layout Issue with the `MentionInput.tsx` component.

Screenshot from 2024-09-22 12-08-46

Screenshot from 2024-09-22 12-07-13

**Comment by MulisaMusehane** [comment]
@hlokomani @TebogoYungMercykay Thanks for cooking me, Kings - please look at the changes I have made.

Fix overlapping text in MentionInput component

- Made textarea background transparent
- Adjusted highlighting div to use invisible text
- Updated highlighting logic to use React elements
- Added styles for proper text wrapping
- Improved accessibility with aria-hidden attribute

These changes resolve the issue of overlapping text while maintaining mention highlighting functionality. The textarea is now the only visible text input, with highlighting applied behind it.

**Review by ShamaKamina — APPROVED** [review]
Nice work Muli. I will make a ticket to replace the mock data. thank you

**Comment by hlokomani** [comment]
> Nice work Muli. I will make a ticket to replace the mock data. thank you

They're already one Shwarm thx

**Comment by MulisaMusehane** [comment]
> Nice work Muli. I will make a ticket to replace the mock data. thank you

Thanks Shama, there is one already : https://github.com/COS301-SE-2024/The-Republic/issues/276#issue-2475101787

**Review by TebogoYungMercykay — APPROVED** [review]

**Pull request merged**
